name: First Workflow
on: workflow_dispatch

jobs:
  First-Job:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Build Stage
        run: mvn clean compile
        
